version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - curl -sS https://getcomposer.org/installer -o composer-installer.php
     

  build:
    commands:
      - echo Building the WordPress application...

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: '.'  # Adjust this if your files are in a subdirectory


