version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      - echo Installing dependencies...
      
  build:
    commands:
      - echo Building the WordPress application...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: '.'  # Adjust this if your files are in a subdirectory

